syntax on
filetype indent plugin on
set background=dark

set tabstop=4
set shiftwidth=4
set smarttab
set expandtab
set softtabstop=4
set autoindent

set noeb vb t_vb=

command W w
command Q q
command WQ wq
command Wq wq

set nu
set hlsearch

nnoremap <silent> <Space> :nohlsearch<CR><Esc>

source /Users/ben/.custom/resources/vim/tslime.vim
