#!/bin/bash

cwd=$(pwd)

vim_options="$@"
python_flag=false
matlab_flag=false
display_flag=false

while getopts 'pmd' flag; do
    case "${flag}" in
        p) python_flag=true ;;
        m) matlab_flag=true ;;
        d) display_flag=true ;;
    esac
done

for arg in "$@"
do
    case $arg in
        *.py) python_flag=true ;;
        *.m) matlab_flag=true ;;
    esac
done

if [ "$display_flag" = true ] ; then
    matlab_options="-display"
else
    matlab_options=""
fi

if [ "$python_flag" = true ] ; then
    vim_options="$vim_options -c 'let pro_lang=\"py\"'"
elif [ "$matlab_flag" = true ] ; then
    vim_options="$vim_options -c 'let pro_lang=\"matlab\"'"
fi

# tmux session name determination
SESH_PREFIX="sesh"
SESH_NUM=0
VALID=0
while [ $VALID == 0 ]; do
    SESH_NAME="$SESH_PREFIX$SESH_NUM"
    tmux has-session -t $SESH_NAME
    if [ $? == 0 ] 
     then
        ((SESH_NUM++))
     else
        VALID=1
    fi
done

# init tmux session
tmux new-session -d -s $SESH_NAME
tmux select-window -t $SESH_NAME:0

# launch vim
tmux send-keys -t $SESH_NAME "vim ${vim_options}" Enter

# launch programming
#tmux split-window -h 'ipython' #if you want exiting ipython to close the pane
tmux split-window -h #if you don't want exiting ipython to close the pane (1/2)
tmux send-keys 'qrsh' Enter
tmux send-keys 'source activate myenv' Enter #ADDED JUST FOR ENVS
tmux send-keys -t $SESH_NAME "cd ${cwd}" Enter
if [ "$python_flag" = true ] ; then
    tmux send-keys 'ipython' Enter #if you don't want exiting ipython to close the pane (2/2)
elif [ "$matlab_flag" = true ] ; then
    tmux send-keys "matlab ${matlab_options}" Enter
else
    tmux send-keys 'clear; echo No programming language chosen.' Enter
fi

# attach tmux
tmux attach-session -t $SESH_NAME
