#!/bin/bash

tmux new-session -d -s vimlab
tmux select-window -t vimlab:0
if [ "$#" -eq  "0" ]
    then
        tmux send-keys -t vimlab "vim" Enter
    else
        tmux send-keys -t vimlab "vim $1" Enter
fi
#tmux split-window -h 'ipython' #if you want exiting ipython to close the pane
tmux split-window -h #if you don't want exiting ipython to close the pane (1/2)
tmux send-keys 'ipython' Enter #if you don't want exiting ipython to close the pane (2/2)
tmux attach-session -t vimlab
